################################################################################
# Release Workflow
# - Triggers on version tags (v*)
# - Builds Python package
# - Creates GitHub Release
# - Publishes to PyPI
# - Uses trusted publishing
################################################################################

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
